"""Baseline schema — created directly from the SQLAlchemy models so the model
definitions stay the single source of truth for the initial install. Subsequent
schema changes must be individual autogenerated migrations.

Revision ID: 0001
Revises:
Create Date: 2026-07-02

"""
from alembic import op

import app.models  # noqa: F401  — register all tables on Base.metadata
from app.db.base import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
